### ISSUE TITLE
Server boot failed

### ISSUE THREAD

**Issue by kamk** [coinblesk/coinblesk-server#16]
An attempt to run the server gives me this error:

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tokenProvider': Unsatisfied dependency expressed through field 'appConfig'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'appConfig': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'coinblesk.url' in string value "${coinblesk.url}"`

I've tried add the coinblesk.url parameter to context.xml such as:
`<Parameter name="coinblesk.url" value="http://192.168.17.101:8080/" />`
but it didn't help.

**Comment by sebastian-stephan** [comment]
When starting the server, you can set the spring profile to 'dev' by setting SPRING_PROFILES_ACTIVE to 'dev':

```sh
SPRING_PROFILES_ACTIVE=dev gradle bootRun # for gradle
SPRING_PROFILES_ACTIVE=dev java -jar  coinblesk-server-2.1-SNAPSHOT.jar # when running the jar
```

This will then load all the necessary config parameters from `src/main/resources/application-dev.properties`

Alternatively you can make a copy of `application-dev.properties` and name it `application.properties`, to copy all the config parameters the default profile.

Hope this helps.

**Comment by kamk** [comment]
Okay, thanks. The server has started, however I can't access it (Whitelabel Error Page):
`2017-02-20 15:43:42.488  WARN 12769 --- [nio-8080-exec-9] o.s.web.servlet.PageNotFound             : No mapping found for HTTP request with URI [/] in DispatcherServlet with name 'dispatcherServlet'`

**Comment by ssc-hrep3** [comment]
@kamk There is no web interface at the moment (therefore the Whitelabel Error Page). There are multiple REST interfaces though.
